# Generated by Django 6.0.4 on 2026-04-29 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('month', models.IntegerField()),
                ('month_name', models.CharField(max_length=20)),
                ('week_of_year', models.IntegerField()),
                ('day', models.IntegerField()),
                ('weekday', models.CharField(max_length=20)),
                ('is_weekend', models.BooleanField()),
                ('is_business_day', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dim_date',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ITSMModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('url_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_itsm_modules', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_itsm_modules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ETLWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.itsmmodule')),
            ],
        ),
        migrations.CreateModel(
            name='ETLConflictLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='analytics.itsmmodule')),
            ],
        ),
        migrations.CreateModel(
            name='CleanedITSMRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=100)),
                ('dynamic_data', models.JSONField()),
                ('etl_processed_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='analytics.itsmmodule')),
            ],
            options={
                'db_table': 'cleaned_records',
            },
        ),
        migrations.CreateModel(
            name='ITSMModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(editable=False, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('url_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_module_configs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_module_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleExtractedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='extracted_files/')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_files', to='analytics.itsmmoduleconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=50)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_measure', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='analytics.itsmmoduleconfig')),
            ],
            options={
                'unique_together': {('module', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='KPIDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aggregation', models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Average'), ('min', 'Min'), ('max', 'Max')], max_length=20)),
                ('filters', models.JSONField(blank=True, default=list)),
                ('filter_value', models.CharField(blank=True, max_length=100, null=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('target_operator', models.CharField(choices=[('=', 'Equal to'), ('>=', 'Greater than or equal to'), ('<=', 'Less than or equal to'), ('>', 'Greater than'), ('<', 'Less than')], default='=', max_length=2)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('value_type', models.CharField(choices=[('number', 'Number'), ('percentage', 'Percentage'), ('duration', 'Duration')], default='number', max_length=20)),
                ('chart_type', models.CharField(choices=[('column', 'Column Chart'), ('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('donut', 'Donut Chart')], default='bar', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpis_definitions', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.itsmmoduleconfig')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_kpis_definitions', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_fields', to='analytics.modulefield')),
                ('filter_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_filters', to='analytics.modulefield')),
                ('group_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_group_by', to='analytics.modulefield')),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aggregation', models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Average'), ('min', 'Min'), ('max', 'Max')], max_length=20)),
                ('filter_value', models.CharField(blank=True, max_length=100, null=True)),
                ('limit', models.IntegerField(blank=True, help_text='Top N results (e.g. 10)', null=True)),
                ('target_operator', models.CharField(choices=[('=', 'Equal to'), ('>', 'Greater than'), ('<', 'Less than'), ('>=', 'Greater than or equal to'), ('<=', 'Less than or equal to')], default='=', max_length=2)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('value_type', models.CharField(choices=[('number', 'Number'), ('percentage', 'Percentage'), ('duration', 'Duration')], default='number', max_length=20)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('pie', 'Pie')], default='bar', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpis', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='analytics.itsmmoduleconfig')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_kpis', to=settings.AUTH_USER_MODEL)),
                ('kpi_definition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dim_kpi', to='analytics.kpidefinition')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.modulefield')),
                ('filter_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_kpis', to='analytics.modulefield')),
                ('group_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grouped_kpis', to='analytics.modulefield')),
            ],
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_field', models.CharField(max_length=150)),
                ('target_field', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='analytics.itsmmodule')),
            ],
            options={
                'unique_together': {('module', 'source_field')},
            },
        ),
        migrations.CreateModel(
            name='KPIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('result_status', models.CharField(choices=[('on_target', 'On Target'), ('off_target', 'Off Target'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('date_dim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.datedimension')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.kpi')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.itsmmodule')),
            ],
            options={
                'unique_together': {('kpi', 'module', 'date_dim')},
            },
        ),
    ]
