# Generated by Django 6.0.4 on 2026-04-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldMapping',
        ),
    ]
