# Generated by Django 6.0.4 on 2026-05-01 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_kpidefinition_reporting_date_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_result_snapshot', models.JSONField(blank=True, null=True)),
                ('risk_level', models.CharField(max_length=20)),
                ('insight', models.TextField()),
                ('probable_cause', models.TextField(blank=True)),
                ('suggested_decision', models.TextField()),
                ('reasoning', models.TextField(blank=True)),
                ('priority', models.CharField(max_length=20)),
                ('confidence', models.FloatField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='analytics.kpidefinition')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.itsmmodule')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
