# Generated by Django 6.0.4 on 2026-05-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_airecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpidefinition',
            name='business_meaning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
