# Generated by Django 6.0.4 on 2026-05-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_kpidefinition_business_meaning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsmmoduleconfig',
            name='url_path',
        ),
        migrations.AddField(
            model_name='itsmmoduleconfig',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='module_uploads/'),
        ),
    ]
