# Generated by Django 6.0.4 on 2026-05-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_remove_itsmmoduleconfig_url_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsmmodule',
            name='url_path',
        ),
        migrations.AddField(
            model_name='itsmmodule',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='module_uploads/'),
        ),
    ]
