# Generated by Django 6.0.4 on 2026-05-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_remove_itsmmodule_url_path_itsmmodule_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='chart_type',
        ),
        migrations.RemoveField(
            model_name='kpidefinition',
            name='chart_type',
        ),
    ]
