# Generated by Django 6.0.4 on 2026-05-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_remove_kpi_chart_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiresult',
            name='grouped_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
