# Generated by Django 6.0.4 on 2026-05-07 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_kpiresult_grouped_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('forecast_value', models.FloatField()),
                ('variance', models.FloatField(blank=True, null=True)),
                ('group_by_field', models.CharField(blank=True, max_length=255, null=True)),
                ('group_by_value', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(default='linear_trend', max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('date_dim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_results', to='analytics.datedimension')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='analytics.kpi')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_forecasts', to='analytics.itsmmodule')),
            ],
            options={
                'ordering': ['date_dim__date'],
                'unique_together': {('kpi', 'module', 'date_dim', 'method')},
            },
        ),
    ]
