# Generated by Django 6.0.4 on 2026-05-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_kpiforecast'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kpiforecast',
            unique_together={('kpi', 'module', 'date_dim', 'group_by_field', 'group_by_value', 'method')},
        ),
    ]
