# Generated by Django 6.0.4 on 2026-05-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_alter_kpiforecast_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpidefinition',
            name='chart_type',
            field=models.CharField(choices=[('card', 'Card'), ('line', 'Line'), ('column', 'Column'), ('bar', 'Bar'), ('pie', 'Pie'), ('donut', 'Donut')], default='line', max_length=20),
        ),
    ]
