# Generated by Django 6.0.4 on 2026-05-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_kpidefinition_chart_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpidefinition',
            name='chart_type',
        ),
    ]
