# Generated by Django 6.0.4 on 2026-05-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_remove_kpidefinition_chart_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsmmodule',
            name='uploaded_file',
        ),
    ]
