# Generated by Django 6.0.4 on 2026-05-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_remove_itsmmodule_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='aggregation',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='field',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='filter_field',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='filter_value',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='group_by',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='module',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='target_operator',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='target_value',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='value_type',
        ),
    ]
