# Generated by Django 6.0.4 on 2026-05-15 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_remove_kpi_aggregation_remove_kpi_created_at_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='kpi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
