# Generated by Django 6.0.4 on 2026-05-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_remove_itsmmodule_created_by_and_more'),
    ]

    operations = [
    
        migrations.RemoveField(
            model_name='kpidefinition',
            name='filter_field',
        ),
        migrations.RemoveField(
            model_name='kpidefinition',
            name='filter_value',
        ),
        migrations.AlterUniqueTogether(
            name='kpiforecast',
            unique_together={('kpi', 'module', 'date_dim', 'group_by_field', 'group_by_value')},
        ),
        migrations.RemoveField(
            model_name='kpiforecast',
            name='method',
        ),
    ]
