# Generated by Django 6.0.4 on 2026-05-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_remove_itsmmodule_created_by_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='kpidefinition',
            name='aggregation',
            field=models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Average'), ('min', 'Min'), ('max', 'Max'), ('percentage', 'Percentage')], max_length=20),
        ),
    ]
