# Generated by Django 6.0.4 on 2026-05-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_remove_itsmmodule_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airecommendation',
            name='user_comment',
        ),
    ]
