# Generated by Django 6.0.4 on 2026-05-11 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermissionChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('granted', 'Granted'), ('revoked', 'Revoked')], max_length=20)),
                ('source', models.CharField(choices=[('role_change', 'Role Change'), ('manual_update', 'Manual Update'), ('request_approval', 'Request Approval')], default='manual_update', max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_changes_made', to=settings.AUTH_USER_MODEL)),
                ('new_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.role')),
                ('old_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.role')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='users.apppermission')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_change_history', to='users.userprofile')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
